### ISSUE TITLE
Solved Meta puzzles should be hidden when the "Hide Solved Puzzles" check box is selected

### ISSUE THREAD

**Issue by nothorian** [cjb/codex-blackboard#125]
Currently solved meta puzzles are not filtered out when "Hide Solved Puzzles" is checked.  These are puzzles just like any other and should be hidden when solved.  If the answers are needed in a Meta Meta then that page will aggregate the meta puzzle names and answers like a normal Meta puzzle.

**Comment by cscott** [comment]
Fixed by b779526a5e022041b28216af5654191f7cd28e1f
