### ISSUE TITLE
Auto-gen tab in gdocs with useful spreadsheet formulas

### ISSUE THREAD

**Issue by dogversioning** [cjb/codex-blackboard#134]
So, not everyone is super skilled with spreadsheets, and a little bit of automation can knock errors/grind way down (I saw this in at least one case this year where a puzzle that people had been stuck on got solved very quickly once I populated in automatic binary -> number -> letter conversion via cell formulas) - it might be useful to have a separate tab generate with each puzzle that has a list of some common operations based on the contents of the cell just to the left of it, which could be copied in very quickly. So, each row might have the following format:

Name of operation/example type of data to be transformed/the cell with the formula in it/explanation text if needed

Here's some operations off the top of my head that would be useful:
-Number to character 
-ASCII code to character
-Character to number
-Binary to number (I did this with a sum of nested ifs on mids of length 1, dunno if there's a cleaner way - but it order for it to work, you need to enforce the column as text to prevent truncation, which probably would need to be explained. Also, it may be useful to have 4 versions for all permutations of read left/right, 1 is logic high/logic low)
-Number to binary
-Caesar shift 
-Resistor color to number (case insensitive is probably best)
-At least one example of mod operand for the truly divorced from data entry
-I'm sure someone can thing of some more

If we don't want to add this here, I would probably look to compile a list of these elsewhere, but the fewer browser tabs to worry about, the better.

**Comment by cscott** [comment]
Rebased and committed: 355df8c9ec346f49f8bac57108b8b5aa97106b8e
