### ISSUE TITLE
Add chat/hunt/spreadsheet shortcut links to blackboard

### ISSUE THREAD

**Issue by cscott** [cjb/codex-blackboard#140]
Every puzzle on the blackboard should have three small icons which are shortcut links to (1) the puzzle chat, (2) the puzzle on the hunt site, and (3) the default puzzle spreadsheet.

In edit mode, you should be able to directly edit the link to the puzzle on the hunt site as a tag. (See issue #139)

**Comment by Torgen** [comment]
Is this not already fixed?

**Comment by cscott** [comment]
Yeah, I think so.
