### ISSUE TITLE
Add 'notes' tag to blackboard for status information.

### ISSUE THREAD

**Issue by cscott** [cjb/codex-blackboard#146]
Issue #55 is going to make the status field into an enumeration.  People still put a lot of free text into into 'status', so we should add a special 'notes' tag which allows more freeform rambling.  (This should be hidden by #142, of course.)

**Comment by Butterwell** [comment]
Tags already have this functionality. We could pre-populate a "Notes" tag. What would be special about the "Notes" tag?

**Comment by cscott** [comment]
Nothing?  I don't know what I was thinking about in particular.  Closing.
