### ISSUE TITLE
"Upload file" button in chat doesn't work

### ISSUE THREAD

**Issue by cscott** [cjb/codex-blackboard#157]
When you press it, it says:
```
Details:
Invalid credentials (missing or invalid oAuth token)
```
This is a regression from last year.  It could possible be related to the meteor upgrade, but I'm guessing that the oAuth token has just expired and needs to be renewed somehow.

See also issue #156 -- we probably need to restructure how we do authentication any way, so it be best just to tackle this at the same time as #156 (unless it's a really easy braindead fix).

**Comment by cjb** [comment]
@cscott Do you remember how it worked before?  I don't see anything in the source tree about passing an oauth token to the clients.  We just have a private GAPI key used by the server..

**Comment by cscott** [comment]
Looks like it used to behave as the docs say, "OAuth authentication only needed for uploading to non-public destinations".  But now they seem to require OAuth for everything, even our public GDrive folders.

So we'll have to copy the OAuth-using code from https://developers.google.com/picker/docs/ it looks like.
