### ISSUE TITLE
Please add option to turn off useless Codexbot stuff but keep useful msgs

### ISSUE THREAD

**Issue by kai-huang** [cjb/codex-blackboard#181]
I see a button in the Codex app for turning off Codexbot, but it turns of all msgs, even useful ones. Can you please add an option to turn off only useless msgs, particularly Codexbot memes?

**Comment by cscott** [comment]
Not trivial, the hubot scripts don't specially tag the meme-related messages in any way.  But a good idea for next year.

**Comment by cscott** [comment]
Closed with 29ca95d1302b8b8f4396189e8548ad005c9e0a32
