### ISSUE TITLE
Porting cscottnet:hubot to Rocket.Chat

### ISSUE THREAD

**Issue by engelgabriel** [cjb/codex-blackboard#196]
Chris, 

Sorry for the issue asking for a hand, but I guess I'd never know until I tried... so I'll be brief.

I started a MIT Open Source, Slack-like, Web Chat called http://rocket.chat built with Meteor. (check it out, you'll like it!)

http://info.meteor.com/blog/a-fistful-of-slack-clones-with-meteor

We made a beta Hubot adapter, that works for Hubot running on their own. (you can see the demo there)

But as I know you'd agree, for some people it would be cumbersome to have to host/run/monitor yet another process to be able to use the hubot.

I am trying to port your cscottnet:hubot + codex-blackboard/server/hubot.coffe to our project, but it is really not my area of expertise.

You'd you guys mind joining the community, just to give us a hand with that?

Thanks for your time anyway!

Gabriel Engel

https://github.com/RocketChat/Rocket.Chat

**Comment by cscott** [comment]
Sorry, the `codex-blackboard` project is a spare-time project we only get to hack on for a few days just before the MIT Mystery Hunt.  I'm afraid we don't have a bunch of time to donate on this project.

**Comment by engelgabriel** [comment]
Nevermind, its done :)
