### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by cjb** [cjb/codex-blackboard#222]
The intrepid mollydb tells us that this repo has no LICENSE file. @cscott, got a preference?

**Comment by cscott** [comment]
I choose GPLv2 by default, but that's because I'm a hippie.

**Comment by cjb** [comment]
AGPL would be hippier :)

That's fine with me, will do a PR sometime.

**Comment by mollydb** [comment]
I also suggest AGPL, due to serve side use.
