### ISSUE TITLE
Implicit CSS-based followups

### ISSUE THREAD

**Issue by Torgen** [cjb/codex-blackboard#230]
Add an attribute to each chat message with the nick of who said it. Then for each user who has ever been in the room, add a style directive like:
media[nick=foo]:not(.bb-message-pm)+media[nick=foo]:not(.bb-message-pm), media[nick=foo].bb-message-pm+media[nick=foo].bb-message-pm { /* hide gravatar */ }
Then you don't need to do any server or client side processing to determine if a message is a followup. You wouldn't even need to store it in the database. And you wouldn't have the issue where someone else's PM that you can't see can break up what should be a followup.

**Comment by Torgen** [comment]
I have a version in a branch that uses a MutationObserver to add or remove the followup class as necessary. I'm guessing it'll be faster, since it doesn't involve O(n) style directives in the number of people who have ever been in the room, but I could implement the CSS version as well if you want to compare.

**Comment by cscott** [comment]
Closed via 4a49b67c5d169f62c1811ddf216f06e9730c37f8
