### ISSUE TITLE
Make link a tag, not a property

### ISSUE THREAD

**Issue by Torgen** [cjb/codex-blackboard#245]
Link is an attribute of the Puzzle/Round/Roundgroup, not a tag, which means you can set it by editing the blackboard, but not with "bot set link [of \<puzzle\>] to foo".

**Comment by cscott** [comment]
It was originally a tag, IIRC, but it was switched to a property to make it easier to write bulk queries to update the link properties (when HQ suddenly releases a new round and the puzzle url prefix suddenly changes).  Bulk operations with minimongo are very cumbersome with the tag object format.

But I couldn't find any self-documentation for this in my chat history or mail, it might not really be an issue now that there's a nice point-and-click way to edit tags.

Still, it's probably easier just to tweak the bot to make "set link of..." work, compared to the effort to tag-ify the link property.

**Comment by Torgen** [comment]
Just noticed this is a dupe of #139.

**Comment by cscott** [comment]
Ah, it looks like my memory was wrong and the link property predates the support for tags in the codebase.  So your original proposal was correct, it should be tag-ified (#139) now that tags are easily editable and such.

It still might be easier to fix the bot than to refactor the link code.  But that's just laziness speaking.

**Comment by cscott** [comment]
(Thanks for the research!)
