### ISSUE TITLE
Memecaptain is down

### ISSUE THREAD

**Issue by Torgen** [cjb/codex-blackboard#251]
memecaptain.com is returning Cloudflare errors, which means triggering a meme in chat makes the bot give you an error. If it's not back by close to the hunt, it should be disabled from cscott/codex-blackboard-hubot-scripts, then a new version shrinkwrapped.

**Comment by cscott** [comment]
We could probably switch to `memegen` alternatively:
https://github.com/github/hubot-scripts/blob/master/src/scripts/meme_generator.coffee

**Comment by cscott** [comment]
According to Jeff: "hmm, last tweet from memecaptain says sorry about the outage today... and its 11 months old"

**Comment by cscott** [comment]
I've removed memecaptain.  I'm hoping to whip together a replacement using memegen.link (https://github.com/jacebrowning/memegen), since all of the other hubot meme modules I could find were also using sites which are currently down/dead.
